### PR TITLE
Upgrade plugin

### PR DESCRIPTION
**Pull request by mkleina**
Summary of changes:
- Glide.lock updated
- Plugin tested in standalone mode and added information about it in readme

### CODE REVIEW

**Comment by kdembler** [comment]
LGTM

**Comment by PatrykMatyjasek** [comment]
@mkleina please update plugin version :)

**Comment by mkleina** [comment]
@PatrykMatyjasek done :+1:

**Comment by PatrykMatyjasek** [comment]
LGTM

**Pull request merged**
